version: '3'
services: 
    devserver:
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
        volumes:
            # - /usr/app/node_modules
            - .:/usr/app
            
    testserver:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - .:/usr/app
        command: ["npm","run","test","--","--coverage"]